name: Tag and Release

on:
  push:
    branches:
      - main
    paths:
      - "lib/tailwind_merge/version.rb"

jobs:
  release:
    env:
      GEM_NAME: tailwind_merge
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_BOT_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Get current version
        id: version-label
        run: |
          VERSION=$(grep VERSION lib/tailwind_merge/version.rb | head -n 1 | cut -d'"' -f2)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # https://github.com/avakar/tag-and-release/pull/7
      - uses: filfreire/tag-and-release@abaaad001eaf803fddce149bb0cc09aef080773f
        with:
          tag_name: ${{ steps.version-label.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        run: script/generate_changelog

      - name: Commit & Push Changelog
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add -f static
          git commit -m "docs: update changelog" || true
          git push

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          bundle exec rake package
          for gem in pkg/tailwind_merge-${{ steps.version-label.outputs.version }}*.gem ; do
            gem push "$gem" --host https://rubygems.org
          done
